#!/bin/bash -xv
cd $HOME/sir/workspace/apache-solr/lucene/build
#mkdir $HOME/sir/workspace/apache-solr/lucenelib
cp ./grouping/lucene-grouping-5.0-SNAPSHOT.jar ../../lucenelib
cp ./grouping/lucene-grouping-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./join/lucene-join-5.0-SNAPSHOT.jar ../../lucenelib
cp ./join/lucene-join-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./benchmark/lucene-benchmark-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./benchmark/lucene-benchmark-5.0-SNAPSHOT.jar ../../lucenelib
cp ./demo/lucene-demo-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./demo/lucene-demo-5.0-SNAPSHOT.jar ../../lucenelib
cp ./classification/lucene-classification-5.0-SNAPSHOT.jar ../../lucenelib
cp ./classification/lucene-classification-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./misc/lucene-misc-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./misc/lucene-misc-5.0-SNAPSHOT.jar ../../lucenelib
cp ./sandbox/lucene-sandbox-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./sandbox/lucene-sandbox-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/phonetic/lucene-analyzers-phonetic-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/phonetic/lucene-analyzers-phonetic-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/icu/lucene-analyzers-icu-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/icu/lucene-analyzers-icu-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/stempel/lucene-analyzers-stempel-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/stempel/lucene-analyzers-stempel-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/common/lucene-analyzers-common-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/common/lucene-analyzers-common-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/uima/lucene-analyzers-uima-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/uima/lucene-analyzers-uima-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/morfologik/lucene-analyzers-morfologik-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/morfologik/lucene-analyzers-morfologik-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/smartcn/lucene-analyzers-smartcn-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/smartcn/lucene-analyzers-smartcn-5.0-SNAPSHOT.jar ../../lucenelib
cp ./analysis/kuromoji/lucene-analyzers-kuromoji-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./analysis/kuromoji/lucene-analyzers-kuromoji-5.0-SNAPSHOT.jar ../../lucenelib
cp ./core/lucene-core-5.0-SNAPSHOT.jar ../../lucenelib
cp ./core/lucene-core-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./memory/lucene-memory-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./memory/lucene-memory-5.0-SNAPSHOT.jar ../../lucenelib
cp ./test-framework/lucene-test-framework-5.0-SNAPSHOT.jar ../../lucenelib
cp ./test-framework/lucene-test-framework-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./queryparser/lucene-queryparser-5.0-SNAPSHOT.jar ../../lucenelib
cp ./queryparser/lucene-queryparser-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./suggest/lucene-suggest-5.0-SNAPSHOT.jar ../../lucenelib
cp ./suggest/lucene-suggest-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./highlighter/lucene-highlighter-5.0-SNAPSHOT.jar ../../lucenelib
cp ./highlighter/lucene-highlighter-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./queries/lucene-queries-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./queries/lucene-queries-5.0-SNAPSHOT.jar ../../lucenelib
cp ./facet/lucene-facet-5.0-SNAPSHOT.jar ../../lucenelib
cp ./facet/lucene-facet-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./spatial/lucene-spatial-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./spatial/lucene-spatial-5.0-SNAPSHOT.jar ../../lucenelib
cp ./replicator/lucene-replicator-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
cp ./replicator/lucene-replicator-5.0-SNAPSHOT.jar ../../lucenelib
cp ./codecs/lucene-codecs-5.0-SNAPSHOT.jar ../../lucenelib
cp ./codecs/lucene-codecs-5.0-SNAPSHOT-javadoc.jar ../../lucenelib
